name: Build

on:
  push:
    branches:
      - '**'
  create:
    branches:
      - 'master'
    tags:
      - '**'

jobs:
  # msvc:
  #   runs-on: windows-2019
  #   steps:
  #   - uses: actions/checkout@v1
  #     with:
  #       fetch-depth: 1
  #   - name: Build the application
  #     shell: bash
  #     run: |
  #       mkdir build
  #       cd build
  #       cmake -DCMAKE_INSTALL_PREFIX=../release -DCMAKE_BUILD_TYPE=Release ..
  #       cmake --build . --config Release -- -m

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libopenblas-dev liblapacke-dev doxygen graphviz libmatio4 libmatio-dev libvtk6-dev lcov
    - name: Build the application
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DBLA_VENDOR=OpenBLAS -DUSE_VTK=ON -DBUILD_DOCUMENTATION=ON ..
        cmake --build . -- -j2
    - name: Test the application
      shell: bash
      run: |
        cd build
        CTEST_OUTPUT_ON_FAILURE=1 ctest .

  macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install the dependencies
      run: |
        brew install cmake gcc hdf5 libmatio boost
    - name: Build the application
      run: |
        mkdir build
        cd build
        cmake -DBLA_VENDOR=Apple ..
        make -j2
    - name: Test the application
      shell: bash
      run: |
        cd build
        CTEST_OUTPUT_ON_FAILURE=1 ctest .
